"""The one rule both tracks share: numbers never travel without their geometry.

A 3-D MRI volume in millimetres and a 2-D pathology tile in microns are
different things, but they fail in the same way: count the elements, forget
the physical size of each one, and every measurement is wrong by a factor
nobody notices until it matters. `ImageBase` is the contract that stops that.

It is deliberately small. It does not try to make a volume and a tile look the
same - a volume has an affine and three axes, a tile has microns-per-pixel and
channel names, and pretending otherwise would hide exactly the details that
matter. It states only what every image in the project must be able to
answer:

- what physical distance one element covers, along each axis, in what unit
- whether the image is synthetic (generated by code) or came from a scanner
- a JSON-safe description a person or a test can read

`Volume` (Track V, `io.py`) and `Tile` (Track P, `pathology/tile.py`) both
inherit from it. Neither changed its name, its fields or its import path when
the base was introduced, so nothing written against them before needed
editing. The everyday version: two different tools that both fit the same
size of socket - not the same tool, but the same fitting.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

import numpy as np


class ImageBase(ABC):
    """What every image in the project must be able to say about itself."""

    data: np.ndarray

    # ---- the geometry contract -------------------------------------------
    @property
    @abstractmethod
    def unit(self) -> str:
        """The physical unit of `spacing`: 'mm' for volumes, 'um' for tiles."""

    @property
    @abstractmethod
    def spacing(self) -> tuple[float, ...]:
        """Physical size of one element along each spatial axis, in `unit`."""

    @property
    def is_synthetic(self) -> bool:
        """True if generated by code. Subclasses override; the default is honest: unknown means no."""
        return False

    # ---- derived, shared ---------------------------------------------------
    @property
    def shape(self) -> tuple[int, ...]:
        return tuple(int(n) for n in self.data.shape)

    @property
    def element_measure(self) -> float:
        """Physical measure of one element: mm^3 for a voxel, um^2 for a pixel."""
        return float(np.prod(self.spacing))

    def describe_geometry(self) -> dict[str, Any]:
        """The part of a description that is the same for every image type."""
        return {
            "shape": list(self.shape),
            "dtype": str(self.data.dtype),
            "spacing": list(self.spacing),
            "unit": self.unit,
            "element_measure": self.element_measure,
            "synthetic": self.is_synthetic,
        }

    def describe_intensities(self) -> dict[str, Any]:
        d = self.data
        return {
            "min": float(np.nanmin(d)),
            "max": float(np.nanmax(d)),
            "mean": float(np.nanmean(d)),
            "n_nonzero": int(np.count_nonzero(d)),
        }
